var currenies = {
    WST : 'Samoan tala',BTN : 'Bhutanese ngultrum',CUC : 'Cuban peso',PGK : 'Papua New Guinean kina',AMD : 'Armenian dram',CVE : 'Cape Verdean escudo',
    LYD : 'Libyan dinar',RWF : 'Rwandan franc',GEL : 'Georgian lari',ERN : 'Eritrean nakfa',KWD : 'Kuwaiti dinar',BHD : 'Bahraini dinar',HTG : 'Haitian gourde',
    MZM : 'Mozambican metical',JOD : 'Jordanian dinar',MRO : 'Mauritanian ouguiya',SLL : 'Sierra Leonean leone',MWK : 'Malawian kwacha',XPF : 'CFP franc',
    RSD : 'Serbian dinar',OMR : 'Omani rial',CRC : 'Costa Rican colon',MNT : 'Mongolian tugrik',NGN : 'Nigerian naira',STD : 'Sao Tome and Principe dobra',
    AOA : 'Angolan kwanza',BIF : 'Burundi franc',LSL : 'Lesotho loti',MMK : 'Myanma kyat',TOP : 'Paanga',VEB : 'Venezuelan bolivar',DZD : 'Algerian dinar',
    CDF : 'Congolese franc',GQE : 'Central African CFA franc',GMD : 'Gambian dalasi',IQD : 'Iraqi dinar',MGA : 'Malagasy ariary',MDL : 'Moldovan leu',MAD : 'Moroccan dirham',
    TRY : 'Turkish new lira',AED : 'UAE dirham',VUV : 'Vanuatu vatu',BDT : 'Bangladeshi taka',ETB : 'Ethiopian birr',KMF : 'Comorian franc',MVR : 'Maldivian rufiyaa',
    SZL : 'Swazi lilangeni',DJF : 'Djiboutian franc',GNF : 'Guinean franc',GHS : 'Ghanaian cedi',ZMK : 'Zambian kwacha',XDR : 'Special Drawing Rights',MOP : 'Macanese pataca',
    TJS : 'Tajikistani somoni',TND : 'Tunisian dinar',TMM : 'Turkmen manat',XOF : 'West African CFA franc',XAF : 'Central African CFA franc',XCD : 'East Caribbean dollar',
    SDG : 'Sudanese pound',ALL : 'Albanian lek',BBD : 'Barbadian dollar',BND : 'Brunei dollar',HUF : 'Hungarian forint',JMD : 'Jamaican dollar',AUD : 'Australian dollar',
    GIP : 'Gibraltar pound',NZD : 'New Zealand dollar',FKP : 'Falkland Islands pound',MKD : 'Macedonian denar',INR : 'Indian rupee',TZS : 'Tanzanian shilling',
    BAM : 'Bosnia and Herzegovina konvertibilna marka',SEK : 'Swedish krona',CNY : 'Chinese renminbi',BSD : 'Bahamian dollar',BWP : 'Botswana pula',LAK : 'Lao kip',
    SYP : 'Syrian pound',CZK : 'Czech koruna',ANG : 'Netherlands Antillean gulden',KRW : 'South Korean won',GTQ : 'Guatemalan quetzal',SOS : 'Somali shilling',
    DKK : 'Danish krone',PEN : 'Peruvian nuevo sol',COP : 'Colombian peso',LBP : 'Lebanese lira',QAR : 'Qatari riyal',BZD : 'Belize dollar',KZT : 'Kazakhstani tenge',
    MUR : 'Mauritian rupee',AWG : 'Aruban florin',KYD : 'Cayman Islands dollar',IDR : 'Indonesian rupiah',EUR : 'European Euro',IRR : 'Iranian rial',ILS : 'Israeli new sheqel',
    MYR : 'Malaysian ringgit',HNL : 'Honduran lempira',PAB : 'Panamanian balboa',PHP : 'Philippine peso',ZAR : 'South African rand',SAR : 'Saudi riyal',SGD : 'Singapore dollar',
    RON : 'Romanian leu',SRD : 'Surinamese dollar',TWD : 'New Taiwan dollar',ARS : 'Argentine peso',AZN : 'Azerbaijani manat',BYR : 'Belarusian ruble',BGN : 'Bulgarian lev',
    BOB : 'Bolivian boliviano',CAD : 'Canadian dollar',CLP : 'Chilean peso',DOP : 'Dominican peso',FJD : 'Fijian dollar',GYD : 'Guyanese dollar',ISK : 'Icelandic kr璐竛a',
    JPY : 'Japanese yen',KPW : 'North Korean won',LVL : 'Latvian lats',CHF : 'Swiss franc',NPR : 'Nepalese rupee',NIO : 'Nicaraguan cordoba',PKR : 'Pakistani rupee',PYG : 'Paraguayan guarani',
    SHP : 'Saint Helena pound',SBD : 'Solomon Islands dollar',LKR : 'Sri Lankan rupee',YER : 'Yemeni rial',TTD : 'Trinidad and Tobago dollar',BRL : 'Brazilian real',HRK : 'Croatian kuna',
    SCR : 'Seychellois rupee',THB : 'Thai baht',AFN : 'Afghan afghani',NOK : 'Norwegian krone',KHR : 'Cambodian riel',EGP : 'Egyptian pound',HKD : 'Hong Kong dollar',LRD : 'Liberian dollar',
    NAD : 'Namibian dollar',RUB : 'Russian ruble',KGS : 'Kyrgyzstani som',PLN : 'Polish zloty',UYU : 'Uruguayan peso',VND : 'Vietnamese dong',KES : 'Kenyan shilling',MXN : 'Mexican peso',
    UGX : 'Ugandan shilling',UZS : 'Uzbekistani som',UAH : 'Ukrainian hryvnia',GBP : 'British pound',USD : 'United States dollar'
};